# Generated by Django 6.0.6 on 2026-06-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
